title: Natalie Castro
email: natalie.castro@colorado.edu
description: >
  I am a Masters Student studying Information Science at the Univerisity of Colorado.
twitter_username: ~
github_username: NatalieRMCastro
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: ~
linkedin_username: natalie-rm-castro
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
mail_username: naca4005@colorado.edu
rss: true
baseurl: /

show_excerpts: true
date_format: "%b %-d, %Y"

logo: assets/images/avatar.png

# Build settings
# theme: jekyll-theme-strata
# remote_theme: mloberg/strata-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pdf-embed
