title: Natalie Castro
email: natalie.castro@colorado.edu
description: >
  I am a student studying sociology, data science, education, and information science. My research interests are: human-centered data science accessible technology, and data generation and visualization. Read more about my experience and my undergraduate research work in my resume/CV or find me on LinkedIn.
twitter_username: ~
github_username: NatalieRMCastro
dribbble_username: ~
facebook_username: ~
flickr_username: ~
instagram_username: ~
linkedin_username: ~
pinterest_username: ~
youtube_username: ~
googleplus_username: ~
rss: true

show_excerpts: true
date_format: "%b %-d, %Y"

logo: https://picsum.photos/123?image=669

# Build settings
# theme: jekyll-theme-strata
# remote_theme: mloberg/strata-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
